trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - task: UseDotNet@2
    displayName: 'Usar SDK de .NET 5.x'
    inputs:
      packageType: 'sdk'
      version: '5.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      npm install
    displayName: 'Ejecutar instalación npm'

  - script: |
      dotnet restore
      dotnet build --configuration Release
      dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Compilar y publicar proyecto .NET'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar artefactos'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'